name = "Cinnamon"
author = "ramidzkh"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9b43f70aa5a3b5f1f9e5fbc8893f873abd8b56ea031f3366851aad5b7d6cf4a"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
