name = "Cinnamon"
author = "ramidzkh"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80ee47e1e33d3955b16b70672cd05b45ec1e0de463abf8400cb7c6def71be3a2"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
