name = "Cinnamon"
author = "ramidzkh"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57e2c32db7a050b3986e880f63af9ee46b4d86afaaf937b423b1141fc5804c92"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
