name = "Cinnamon"
author = "ramidzkh"
version = "2.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "401f380a35cd241d96df9c25df981870d0380639a510eec4ec72564b31c356b1"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
