name = "Cinnamon"
author = "ramidzkh"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0c5ab169a970c9073823fbdb9ba2dfe3f3261aa67dd7c32503eacee5866a9ff"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
