name = "Cinnamon"
author = "ramidzkh"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34f21895c4af66126d60d9ce425a4ed579174ec90892ddc04321e00f5c12fe23"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
