name = "Cinnamon"
author = "ramidzkh"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "471f3ac9f37fade40ebcfd9021c99bf40221dc8a4b817f81801c9355069374b4"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
