name = "Cinnamon"
author = "ramidzkh"
version = "2.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d74ceda589cbccb258796e9aa5a5f8a9a34c127fe4cb1e41ca4204908b1cd5d"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
