name = "Cinnamon"
author = "ramidzkh"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "840c67289f749b0e2aa05751881c6a9abe03dd006f5a37f4a002f57156b3f627"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
