name = "Cinnamon"
author = "ramidzkh"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d29d0b82364fc30a66bd9ce0194ea42428b194a66a430ced39acf0a36997eb43"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
