name = "Cinnamon"
author = "ramidzkh"
version = "2.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1388a66cd5d1fe9836142191ba89d2b93939cb2283da557025d6e14d08b0c9fc"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
