name = "Cinnamon"
author = "ramidzkh"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "375aaeb3336f0e5636263604d6873fbb5958936623338d46cfc937b4d4468149"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
