name = "Cinnamon"
author = "ramidzkh"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "570edd2877b3953f2ff517beea1546d4381b6c9bf7d160af90bfacec85341ed8"

[versions]
forge = "36.2.2"
minecraft = "1.16.5"
