name = "Cinnamon"
author = "ramidzkh"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56439bc4e9a53261840e5aaf6149331d2b821927c5ac9135a6ea3417d7b6f0a7"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
