name = "Angel Block"
filename = "angelblock-3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3176/624/angelblock-3.0.jar"
hash-format = "murmur2"
hash = "2235842165"

[update]
[update.curseforge]
file-id = 3176624
project-id = 332817
release-channel = "beta"
