name = "AppleSkin"
filename = "appleskin-forge-mc1.18-2.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3686/482/appleskin-forge-mc1.18-2.4.0.jar"
hash-format = "sha1"
hash = "36c297edae79cd9c33ce3cdb2230bc36fd9523f0"

[update]
[update.curseforge]
file-id = 3686482
project-id = 248787
