name = "Applied Energistics 2"
filename = "appliedenergistics2-8.4.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3590/406/appliedenergistics2-8.4.6.jar"
hash-format = "murmur2"
hash = "835222383"

[update]
[update.curseforge]
file-id = 3590406
project-id = 223794
release-channel = "beta"
