name = "Bookshelf"
filename = "Bookshelf-Forge-1.16.5-10.3.29.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3474/499/Bookshelf-Forge-1.16.5-10.3.29.jar"
hash-format = "murmur2"
hash = "3146577677"

[update]
[update.curseforge]
file-id = 3474499
project-id = 228525
release-channel = "beta"
