name = "Extreme sound muffler (Forge)"
filename = "extremeSoundMuffler-3.17_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3506/112/extremeSoundMuffler-3.17_1.16.5.jar"
hash-format = "murmur2"
hash = "586800759"

[update]
[update.curseforge]
file-id = 3506112
project-id = 363363
release-channel = "beta"
