name = "Extreme sound muffler (Forge)"
filename = "extremeSoundMuffler-3.24_Forge-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3648/159/extremeSoundMuffler-3.24_Forge-1.18.1.jar"
hash-format = "sha1"
hash = "daf8e8b25cecc35332a8b5829594ff7b50243890"

[update]
[update.curseforge]
file-id = 3648159
project-id = 363363
