name = "FTB Chunks (Forge)"
filename = "ftb-chunks-forge-1605.3.1-build.41.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3409/573/ftb-chunks-forge-1605.3.1-build.41.jar"
hash-format = "murmur2"
hash = "2776905832"

[update]
[update.curseforge]
file-id = 3409573
project-id = 314906
release-channel = "beta"
