name = "FTB Chunks (Forge)"
filename = "ftb-chunks-forge-1802.3.5-build.130.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3725/654/ftb-chunks-forge-1802.3.5-build.130.jar"
hash-format = "sha1"
hash = "ed827ccfb2629b818c2da54d5364c6b3cd173aae"

[update]
[update.curseforge]
file-id = 3725654
project-id = 314906
