name = "FTB Teams (Forge)"
filename = "ftb-teams-forge-1802.2.6-build.51.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3725/501/ftb-teams-forge-1802.2.6-build.51.jar"
hash-format = "sha1"
hash = "822e59c0fb2e50ce102350caaa6955d493c94c37"

[update]
[update.curseforge]
file-id = 3725501
project-id = 404468
