name = "FTB Chunks (Forge)"
filename = "ftb-chunks-forge-1605.3.2-build.91.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3590/598/ftb-chunks-forge-1605.3.2-build.91.jar"
hash-format = "murmur2"
hash = "3173283240"

[update]
[update.curseforge]
file-id = 3590598
project-id = 314906
release-channel = "beta"
