name = "FTB Teams (Forge)"
filename = "ftb-teams-forge-1605.2.2-build.24.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3453/698/ftb-teams-forge-1605.2.2-build.24.jar"
hash-format = "murmur2"
hash = "3719209000"

[update]
[update.curseforge]
file-id = 3453698
project-id = 404468
release-channel = "beta"
