name = "GraveStone Mod"
filename = "gravestone-1.16.5-1.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3289/916/gravestone-1.16.5-1.0.6.jar"
hash-format = "murmur2"
hash = "1783849258"

[update]
[update.curseforge]
file-id = 3289916
project-id = 238551
release-channel = "beta"
