name = "Just Enough Items (JEI)"
filename = "jei-1.16.5-7.7.1.118.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3414/898/jei-1.16.5-7.7.1.118.jar"
hash-format = "murmur2"
hash = "2938617462"

[update]
[update.curseforge]
file-id = 3414898
project-id = 238222
release-channel = "beta"
