name = "JourneyMap"
filename = "journeymap-1.18.2-5.8.1-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3756/50/journeymap-1.18.2-5.8.1-forge.jar"
hash-format = "sha1"
hash = "5cd61c4d4b2ba85507325c99f714a160180e9562"

[update]
[update.curseforge]
file-id = 3756050
project-id = 32274
