name = "JourneyMap"
filename = "journeymap-1.18.2-5.8.2-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3764/158/journeymap-1.18.2-5.8.2-forge.jar"
hash-format = "sha1"
hash = "0d5abccc0c164bbd638ec22220c09cb987c33d16"

[update]
[update.curseforge]
file-id = 3764158
project-id = 32274
