name = "KubeJS (Forge)"
filename = "kubejs-forge-1802.5.1-build.353.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3764/767/kubejs-forge-1802.5.1-build.353.jar"
hash-format = "sha1"
hash = "c9fe13cfd0645b62160a0c991d61c321ba2a38b8"

[update]
[update.curseforge]
file-id = 3764767
project-id = 238086
