name = "KubeJS (Forge)"
filename = "kubejs-forge-1605.3.15-build.106.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3445/496/kubejs-forge-1605.3.15-build.106.jar"
hash-format = "murmur2"
hash = "2182852964"

[update]
[update.curseforge]
file-id = 3445496
project-id = 238086
release-channel = "beta"
