name = "KubeJS (Forge)"
filename = "kubejs-forge-1605.3.15-build.90.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3429/427/kubejs-forge-1605.3.15-build.90.jar"
hash-format = "murmur2"
hash = "3201946875"

[update]
[update.curseforge]
file-id = 3429427
project-id = 238086
release-channel = "beta"
