name = "KubeJS (Forge)"
filename = "kubejs-forge-1605.3.15-build.110.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3455/590/kubejs-forge-1605.3.15-build.110.jar"
hash-format = "murmur2"
hash = "2918967795"

[update]
[update.curseforge]
file-id = 3455590
project-id = 238086
release-channel = "beta"
