name = "Light Overlay (Rift/Forge/Fabric)"
filename = "light-overlay-6.0.5-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3669/531/light-overlay-6.0.5-forge.jar"
hash-format = "sha1"
hash = "b1db8b81ba6ce64c062f673e87bc0c65ec0bf9e7"

[update]
[update.curseforge]
file-id = 3669531
project-id = 325492
