name = "Mekanism Generators"
filename = "MekanismGenerators-1.16.5-10.1.1.456.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3590/101/MekanismGenerators-1.16.5-10.1.1.456.jar"
hash-format = "murmur2"
hash = "1831094382"

[update]
[update.curseforge]
file-id = 3590101
project-id = 268566
release-channel = "beta"
