name = "Nature's Compass"
filename = "NaturesCompass-1.18.2-1.9.5-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3684/917/NaturesCompass-1.18.2-1.9.5-forge.jar"
hash-format = "sha1"
hash = "a26c57771577844382519c320876d773c28e6626"

[update]
[update.curseforge]
file-id = 3684917
project-id = 252848
