name = "Rhino"
filename = "rhino-forge-1801.1.9-build.135.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3742/385/rhino-forge-1801.1.9-build.135.jar"
hash-format = "sha1"
hash = "5241b1b410d0c00ce68100b269724bcaab378627"

[update]
[update.curseforge]
file-id = 3742385
project-id = 416294
