name = "Rhino"
filename = "rhino-forge-1605.1.3-build.54.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3453/580/rhino-forge-1605.1.3-build.54.jar"
hash-format = "murmur2"
hash = "4121709858"

[update]
[update.curseforge]
file-id = 3453580
project-id = 416294
release-channel = "beta"
