name = "Simple Storage Network"
filename = "SimpleStorageNetwork-1.18.2-1.6.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3693/704/SimpleStorageNetwork-1.18.2-1.6.1.jar"
hash-format = "sha1"
hash = "262b0a1658c21efe5c6e91de43aaae636f17d293"

[update]
[update.curseforge]
file-id = 3693704
project-id = 268495
