name = "Storage Drawers"
filename = "StorageDrawers-1.16.3-8.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3402/515/StorageDrawers-1.16.3-8.3.0.jar"
hash-format = "murmur2"
hash = "1640644228"

[update]
[update.curseforge]
file-id = 3402515
project-id = 223852
release-channel = "beta"
