name = "Storage Drawers"
filename = "StorageDrawers-1.16.3-8.5.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3580/837/StorageDrawers-1.16.3-8.5.0.jar"
hash-format = "murmur2"
hash = "3272079233"

[update]
[update.curseforge]
file-id = 3580837
project-id = 223852
release-channel = "beta"
