name = "Storage Drawers"
filename = "StorageDrawers-1.18.2-10.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3693/181/StorageDrawers-1.18.2-10.2.0.jar"
hash-format = "sha1"
hash = "1dc1f64c1ad31db14a613778ca3cc4a2afd452f3"

[update]
[update.curseforge]
file-id = 3693181
project-id = 223852
