name = "Tinkers Construct"
filename = "TConstruct-1.16.5-3.1.1.252.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3412/365/TConstruct-1.16.5-3.1.1.252.jar"
hash-format = "murmur2"
hash = "3271888402"

[update]
[update.curseforge]
file-id = 3412365
project-id = 74072
release-channel = "beta"
