name: Curseforge Pack Export
on:
  - push

jobs:
  build:
    name: Export
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
      - name: Setup packwiz
        run: GOBIN=/usr/local/bin/ go install github.com/packwiz/packwiz@latest
      - name: Export pack
        run: packwiz curseforge export
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Cinnamon
          path: Cinnamon*.zip
